backup_vm.py: fix download backup disk command
Download backup disk command failed when used after
starting a backup due to missing argument.

Traceback (most recent call last):
  File "./backup_vm.py", line 502, in <module>
    main()
  File "./backup_vm.py", line 174, in main
    args.command(args)
  File "./backup_vm.py", line 253, in cmd_download
    connection, args.backup_uuid, args, incremental=args.incremental)
  File "./backup_vm.py", line 368, in download_backup
    if not args.download_backup:
AttributeError: 'Namespace' object has no attribute 'download_backup'

This patch fixes the error by setting the missing argument.

Change-Id: I69841a94f5cc0adaf5607c0f36d3730908135482
Signed-off-by: Eyal Shenitzky <eshenitz@redhat.com>